services:
  postgres:
    image: postgres:15.10
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crud
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data